spring:
    h2:
        console:
            enabled: 'true'
    datasource:
        username: sa
        url: jdbc:h2:~/bike-me-now
        driverClassName: org.h2.Driver
        password: sa
    jpa:
        show-sql: 'true'
        hibernate:
            ddl-auto: create
